linters-settings:
  #check:
  #check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow # not important for now
      - unnamedResult # not important
      - hugeParam #to be checked
      - commentFormatting
      - paramTypeCombine

  govet:
    enable:
      - appends
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - deepequalerrors
      - defers
      - directive
      - errorsas
      #      - fieldalignment
      - findcall
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      #      - nilness
      - printf
      - reflectvaluecompare
      - shadow
      - shift
      - sigchanyzer
      - slog
      - sortslice
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
      - unusedwrite

  revive:
    rules:
      - name: exported
        disabled: true

  wsl:
    allow-assign-and-anything: true
    allow-cuddle-declarations: true # should be false
    allow-separated-leading-comment: true

  nolintlint:
    allow-no-explanation: []
    require-explanation: false
    require-specific: false

  gosec:
    excludes:
      - G601 # performance issue: https://github.com/golangci/golangci-lint/issues/4735
      - G113 # performance issue: https://github.com/golangci/golangci-lint/issues/4735

  predeclared:
    ignore: 'error'

  mnd:
    ignored-functions:
      - 'math.*' # Magic number generation, should be fixed and removed?

  stylecheck:
    checks:
      - all
      - '-ST1003'

linters:
  disable-all: true
  enable:
    - bodyclose
    #- depguard #We should create a correct config to enabe depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gofmt
    - gocyclo
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    # - mnd # Magic numbers should be fixed and enable gomnd,
    - nakedret
    # - nolintlint # Current issue with the nolintlint linter (https://github.com/golangci/golangci-lint/issues/1940)
    - nakedret
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - staticcheck
    #- structcheck #The owner seems to have abandoned the linter.
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    # - wrapcheck # 3th party errors should be wrapped to not lose context
    - wsl

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - cdk/
  exclude-files:
    - '(.+)wire_gen\.go'
  uniq-by-line: false

output:
  path-prefix: ''
  sort-results: true
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true